--- #YAML:1.0
name:                CPAN-Test-Dummy-Perl5-Make-ConfReq
version:             1.00
abstract:            CPAN Test Dummy for CPAN.pm
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32_01 and tweaked manually
configure_requires:
  'CPAN::Test::Dummy::Perl5::Make': 1.05
distribution_type:   module
requires:     
  'CPAN::Test::Dummy::Perl5::Make': 1.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
